version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.4
jobs:
  build:
    docker:

      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn run build

      - run: mv public zq-zone

      - persist_to_workspace:
          root: ~/repo
          paths:
            - zq-zone
  deploy:
    machine:
      enabled: true
    steps:
      - run: sudo apt-get update && sudo apt-get install rsync
      - attach_workspace:
          at: ~/repo
      - add_ssh_keys:
          fingerprints:
            - "2a:74:8c:f4:0a:f0:47:35:9a:de:a8:d8:52:70:84:18"
      - run: cd ~/repo/zq-zone && ls
      - run:
          name: Deploy Over SSH
          command: |
            rsync -va --delete ~/repo/zq-zone/ $BEAF_USER@$BEAF_HOST:/usr/web/zq-zone/deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
